<?php
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function slider_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'slider_block':
      return '<p>' . t('Slider Block') . '</p>';
  }
}
/**
 * Implements hook_theme().
 */
function slider_block_theme($existing, $type, $theme, $path) {
  return ['slider-block' =>
    [
      'variables' => [
        'slider_name' => 'slider_name',
        'subtitle' => 'subtitle',
        'image_url' => 'image_url',
      ],
    ]
  ];
}
